// <auto-generated>
// Code generated by LUISGen Assets\LU\models\LUIS\cafeLUISModel.json -cs Luis.cafeLUISModel -o .
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
namespace Luis
{
    public class cafeLUISModel: Microsoft.Bot.Builder.Core.Extensions.IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            Book_Table, 
            Greeting, 
            None, 
            Who_are_you_intent
        };
        public Dictionary<Intent, Microsoft.Bot.Builder.Ai.LUIS.IntentData> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] PartySize;

            // Built-in entities
            public Microsoft.Bot.Builder.Ai.LUIS.DateTimeSpec[] Builtin_datetime;
            public double[] Builtin_number;

            // Lists
            public string[][] CafeLocation;

            // Instance
            public class _Instance
            {
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] PartySize;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] Builtin_datetime;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] Builtin_number;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] CafeLocation;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<cafeLUISModel>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }
    }
}
